/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  UserManagementApi,
  UserManagementV2Api,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierUserManagementCustom } from "./client-custom";

export class VisierUserManagement extends VisierUserManagementCustom {
  readonly userManagement: UserManagementApi;
  readonly userManagementV2: UserManagementV2Api;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.userManagement = new UserManagementApi(configuration);
    this.userManagementV2 = new UserManagementV2Api(configuration);
  }

}
