/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdditionalCapabilitiesDTO
 */
export interface AdditionalCapabilitiesDTO {
    /**
     * The additional capabilities assigned to this profile.
     * @type {Array<string>}
     * @memberof AdditionalCapabilitiesDTO
     */
    'additionalCapabilities'?: Array<string>;
}

