/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionAssignedForLocalTenantDTO } from './permission-assigned-for-local-tenant-dto';

/**
 * 
 * @export
 * @interface AllPermissionsAssignedForLocalTenantDTO
 */
export interface AllPermissionsAssignedForLocalTenantDTO {
    /**
     * A list of objects representing the user\'s permissions.
     * @type {Array<PermissionAssignedForLocalTenantDTO>}
     * @memberof AllPermissionsAssignedForLocalTenantDTO
     */
    'assignedPermissions'?: Array<PermissionAssignedForLocalTenantDTO>;
}

