/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGroupAssignedForLocalTenantDTO } from './user-group-assigned-for-local-tenant-dto';

/**
 * 
 * @export
 * @interface AllUserGroupsAssignedForLocalTenantDTO
 */
export interface AllUserGroupsAssignedForLocalTenantDTO {
    /**
     * A list of objects representing the available user groups.
     * @type {Array<UserGroupAssignedForLocalTenantDTO>}
     * @memberof AllUserGroupsAssignedForLocalTenantDTO
     */
    'assignedUserGroups'?: Array<UserGroupAssignedForLocalTenantDTO>;
}

