/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProfileAssignedForLocalTenantDTO } from './profile-assigned-for-local-tenant-dto';

/**
 * 
 * @export
 * @interface AllProfileAssignedForLocalTenantDTO
 */
export interface AllProfileAssignedForLocalTenantDTO {
    /**
     * A list of objects representing the user profiles assigned to the user and their validity range.
     * @type {Array<ProfileAssignedForLocalTenantDTO>}
     * @memberof AllProfileAssignedForLocalTenantDTO
     */
    'assignedProfiles'?: Array<ProfileAssignedForLocalTenantDTO>;
}

