/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGetAPIResponseDTO } from './user-get-apiresponse-dto';

/**
 * 
 * @export
 * @interface AllUsersGetAPIResponseDTO
 */
export interface AllUsersGetAPIResponseDTO {
    /**
     * A list of available users.
     * @type {Array<UserGetAPIResponseDTO>}
     * @memberof AllUsersGetAPIResponseDTO
     */
    'users'?: Array<UserGetAPIResponseDTO>;
    /**
     * The number of results to return. The maximum number of users to retrieve is 1000.
     * @type {number}
     * @memberof AllUsersGetAPIResponseDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof AllUsersGetAPIResponseDTO
     */
    'start'?: number;
}

