/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignRevokePermissionByUserDTO } from './assign-revoke-permission-by-user-dto';
import { PermissionAssignedForLocalTenantDTO } from './permission-assigned-for-local-tenant-dto';

/**
 * The results of the permission assignment or removal.
 * @export
 * @interface AssignRevokePermissionByPermissionDTO
 */
export interface AssignRevokePermissionByPermissionDTO {
    /**
     * 
     * @type {PermissionAssignedForLocalTenantDTO}
     * @memberof AssignRevokePermissionByPermissionDTO
     */
    'permission'?: PermissionAssignedForLocalTenantDTO;
    /**
     * A list of objects representing the users that was permission was assigned to or removed from.
     * @type {Array<AssignRevokePermissionByUserDTO>}
     * @memberof AssignRevokePermissionByPermissionDTO
     */
    'users'?: Array<AssignRevokePermissionByUserDTO>;
}

