/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignRevokePermissionByTenantDTO } from './assign-revoke-permission-by-tenant-dto';

/**
 * The results of the permission assignment or removal.
 * @export
 * @interface AssignRevokePermissionsResponseDTO
 */
export interface AssignRevokePermissionsResponseDTO {
    /**
     * A list of objects representing the users that were assigned permissions, organized by the tenants the users belong to.
     * @type {Array<AssignRevokePermissionByTenantDTO>}
     * @memberof AssignRevokePermissionsResponseDTO
     */
    'tenants'?: Array<AssignRevokePermissionByTenantDTO>;
}

