/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Permission } from './permission';

/**
 * 
 * @export
 * @interface AssignRevokePermissionsRequest
 */
export interface AssignRevokePermissionsRequest {
    /**
     * A list of objects representing the permissions to assign to or remove from users.
     * @type {Array<Permission>}
     * @memberof AssignRevokePermissionsRequest
     */
    'permissions'?: Array<Permission>;
}

