/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CapabilitiesDTO
 */
export interface CapabilitiesDTO {
    /**
     * The name of the capability.
     * @type {string}
     * @memberof CapabilitiesDTO
     */
    'capability'?: string;
    /**
     * The access level of the profile for the given capability.
     * @type {string}
     * @memberof CapabilitiesDTO
     */
    'accessLevel'?: string;
    /**
     * The view level of the profile for the given capability.
     * @type {string}
     * @memberof CapabilitiesDTO
     */
    'viewLevel'?: string;
}

