/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LastLoginDTO
 */
export interface LastLoginDTO {
    /**
     * The time that the user last logged into Visier.
     * @type {string}
     * @memberof LastLoginDTO
     */
    'timestamp'?: string;
}

