/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGroupGetAPIResponseDTO } from './user-group-get-apiresponse-dto';

/**
 * 
 * @export
 * @interface PermissionsToUserGroupForTenantDTO
 */
export interface PermissionsToUserGroupForTenantDTO {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof PermissionsToUserGroupForTenantDTO
     */
    'tenantCode'?: string;
    /**
     * The state of the permission assignment or removal. Valid values are Succeed or Failed.
     * @type {string}
     * @memberof PermissionsToUserGroupForTenantDTO
     */
    'status'?: string;
    /**
     * A detailed description of the request outcome, if available.
     * @type {string}
     * @memberof PermissionsToUserGroupForTenantDTO
     */
    'message'?: string;
    /**
     * A list of objects representing user groups and the permissions to assign to or remove from them.
     * @type {Array<UserGroupGetAPIResponseDTO>}
     * @memberof PermissionsToUserGroupForTenantDTO
     */
    'userGroups'?: Array<UserGroupGetAPIResponseDTO>;
}

