/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionsToUserGroupRequestDTO } from './permissions-to-user-group-request-dto';

/**
 * 
 * @export
 * @interface PermissionsToUserGroupsRequestDTO
 */
export interface PermissionsToUserGroupsRequestDTO {
    /**
     * A list of objects representing the user groups and permissions to assign or remove.
     * @type {Array<PermissionsToUserGroupRequestDTO>}
     * @memberof PermissionsToUserGroupsRequestDTO
     */
    'userGroups'?: Array<PermissionsToUserGroupRequestDTO>;
}

