/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionAssignedUserDTO } from './permission-assigned-user-dto';

/**
 * The users assigned a specific permission, grouped by tenant.
 * @export
 * @interface PermissionAssignedByTenantDTO
 */
export interface PermissionAssignedByTenantDTO {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof PermissionAssignedByTenantDTO
     */
    'tenantCode'?: string;
    /**
     * A list of objects representing the users that the permission is assigned to.
     * @type {Array<PermissionAssignedUserDTO>}
     * @memberof PermissionAssignedByTenantDTO
     */
    'users'?: Array<PermissionAssignedUserDTO>;
}

