/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PermissionResponseDTO
 */
export interface PermissionResponseDTO {
    /**
     * The unique identifier associated with the permission.
     * @type {string}
     * @memberof PermissionResponseDTO
     */
    'permissionId'?: string;
    /**
     * An identifiable permission name to display in Visier, such as \"Diversity Access\".
     * @type {string}
     * @memberof PermissionResponseDTO
     */
    'displayName'?: string;
}

