/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The user and the method through which the user was assigned the permission.
 * @export
 * @interface PermissionAssignedUserDTO
 */
export interface PermissionAssignedUserDTO {
    /**
     * The unique identifier associated with the user.
     * @type {string}
     * @memberof PermissionAssignedUserDTO
     */
    'userId'?: string;
    /**
     * The user\'s username. This is typically the user\'s email, such as john@visier.com.
     * @type {string}
     * @memberof PermissionAssignedUserDTO
     */
    'username'?: string;
    /**
     * The method through which the user was assigned the permission. The permission may be assigned through  the following options:   - User: The permission was directly assigned to the user.   - UserGroup: The permission was assigned because the user belongs to a user group that is assigned the permission.   - UserAndUserGroup: The permission was directly assigned to the user and assigned because the user belongs to     a user group that is assigned the permission.
     * @type {string}
     * @memberof PermissionAssignedUserDTO
     */
    'permissionFrom'?: string;
}

