/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * The unique identifier associated with a permission.
     * @type {string}
     * @memberof Permission
     */
    'permissionId'?: string;
    /**
     * A list of strings representing unique user IDs.
     * @type {Array<string>}
     * @memberof Permission
     */
    'userIds'?: Array<string>;
}

