/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionAssignedByTenantDTO } from './permission-assigned-by-tenant-dto';

/**
 * Users that are assigned a specific permission.
 * @export
 * @interface PermissionAssignedUsersDTO
 */
export interface PermissionAssignedUsersDTO {
    /**
     * A list of objects representing the users that are assigned the specific permission, organized by the tenants the users belong to.
     * @type {Array<PermissionAssignedByTenantDTO>}
     * @memberof PermissionAssignedUsersDTO
     */
    'tenants'?: Array<PermissionAssignedByTenantDTO>;
    /**
     * The number of results to return. The maximum number of tenants to retrieve is 100.
     * @type {number}
     * @memberof PermissionAssignedUsersDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof PermissionAssignedUsersDTO
     */
    'start'?: number;
}

