/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PermissionsToUserGroupRequestDTO
 */
export interface PermissionsToUserGroupRequestDTO {
    /**
     * The unique identifier associated with the user group.
     * @type {string}
     * @memberof PermissionsToUserGroupRequestDTO
     */
    'userGroupId'?: string;
    /**
     * A list of strings representing the unique permission IDs to assign.
     * @type {Array<string>}
     * @memberof PermissionsToUserGroupRequestDTO
     */
    'permissionsIds'?: Array<string>;
}

