/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdditionalCapabilitiesDTO } from './additional-capabilities-dto';
import { CapabilitiesDTO } from './capabilities-dto';

/**
 * 
 * @export
 * @interface ProfileAssignedForLocalTenantDTO
 */
export interface ProfileAssignedForLocalTenantDTO {
    /**
     * The unique identifier associated with the profile.
     * @type {string}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'profileId'?: string;
    /**
     * An identifiable profile name to display in Visier, such as \"Partner Service Manager\".
     * @type {string}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'displayName'?: string;
    /**
     * An inclusive date-time when this profile is active.
     * @type {string}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'validityStartTime'?: string;
    /**
     * An exclusive date-time when this profile is no longer active.
     * @type {string}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'validityEndTime'?: string;
    /**
     * A list of objects representing the access that this profile has for the capabilities of this profile.
     * @type {Array<CapabilitiesDTO>}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'capabilities'?: Array<CapabilitiesDTO>;
    /**
     * A list of the additional capabilities that are assigned to this profile.
     * @type {AdditionalCapabilitiesDTO}
     * @memberof ProfileAssignedForLocalTenantDTO
     */
    'additionalCapabilities'?: AdditionalCapabilitiesDTO;
}

