/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SimpleUserDTO
 */
export interface SimpleUserDTO {
    /**
     * The unique identifier associated with the user.
     * @type {string}
     * @memberof SimpleUserDTO
     */
    'userId'?: string;
    /**
     * The user\'s username. This is typically the user\'s email, such as john@visier.com.
     * @type {string}
     * @memberof SimpleUserDTO
     */
    'username'?: string;
}

