/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserSecurityAssignmentsDTO } from './user-security-assignments-dto';

/**
 * 
 * @export
 * @interface TenantAssignmentsDTO
 */
export interface TenantAssignmentsDTO {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof TenantAssignmentsDTO
     */
    'tenantCode'?: string;
    /**
     * The state of the user group assignment. Valid values are Succeed or Failed.
     * @type {string}
     * @memberof TenantAssignmentsDTO
     */
    'status'?: TenantAssignmentsDTOStatusEnum;
    /**
     * A detailed description of the request outcome, if available.
     * @type {string}
     * @memberof TenantAssignmentsDTO
     */
    'message'?: string;
    /**
     * A list of objects representing the user group and user assignments.
     * @type {Array<UserSecurityAssignmentsDTO>}
     * @memberof TenantAssignmentsDTO
     */
    'assignments'?: Array<UserSecurityAssignmentsDTO>;
}

type TenantAssignmentsDTOStatusEnum = 'Unknown' | 'Succeed' | 'Failed'


