/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserUpdateAPIRequestDTO
 */
export interface UserUpdateAPIRequestDTO {
    /**
     * An identifiable name to display within Visier. For example, \"John Smith\".
     * @type {string}
     * @memberof UserUpdateAPIRequestDTO
     */
    'displayName'?: string;
    /**
     * If applicable, and if available, the user employee ID in the data.
     * @type {string}
     * @memberof UserUpdateAPIRequestDTO
     */
    'employeeId'?: string;
    /**
     * If true, the user account is enabled.
     * @type {string}
     * @memberof UserUpdateAPIRequestDTO
     */
    'accountEnabled'?: string;
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof UserUpdateAPIRequestDTO
     */
    'email'?: string;
}

