/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionResponseDTO } from './permission-response-dto';

/**
 * 
 * @export
 * @interface UserGroupGetAPIResponseDTO
 */
export interface UserGroupGetAPIResponseDTO {
    /**
     * The unique identifier associated with the user group.
     * @type {string}
     * @memberof UserGroupGetAPIResponseDTO
     */
    'userGroupId'?: string;
    /**
     * An identifiable user group name to display in Visier, such as \"Leadership User Group\".
     * @type {string}
     * @memberof UserGroupGetAPIResponseDTO
     */
    'displayName'?: string;
    /**
     * A list of objects representing the user\'s permissions.
     * @type {Array<PermissionResponseDTO>}
     * @memberof UserGroupGetAPIResponseDTO
     */
    'permissions'?: Array<PermissionResponseDTO>;
}

