/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SimpleUserDTO } from './simple-user-dto';

/**
 * 
 * @export
 * @interface UserSecurityAssignmentsDTO
 */
export interface UserSecurityAssignmentsDTO {
    /**
     * The unique identifier associated with the user group.
     * @type {string}
     * @memberof UserSecurityAssignmentsDTO
     */
    'id'?: string;
    /**
     * The name of the user group.
     * @type {string}
     * @memberof UserSecurityAssignmentsDTO
     */
    'name'?: string;
    /**
     * A list of objects representing the users assigned to or removed from the user group.
     * @type {Array<SimpleUserDTO>}
     * @memberof UserSecurityAssignmentsDTO
     */
    'users'?: Array<SimpleUserDTO>;
}

