/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SimpleUserDTO } from './simple-user-dto';

/**
 * 
 * @export
 * @interface UserGroupsUsersForTenantDTO
 */
export interface UserGroupsUsersForTenantDTO {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof UserGroupsUsersForTenantDTO
     */
    'tenantCode'?: string;
    /**
     * A list of objects representing the users in the user group.
     * @type {Array<SimpleUserDTO>}
     * @memberof UserGroupsUsersForTenantDTO
     */
    'users'?: Array<SimpleUserDTO>;
}

