/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsersUpdateAPIUserDTO } from './users-update-apiuser-dto';

/**
 * 
 * @export
 * @interface UsersUpdateAPIRequestDTO
 */
export interface UsersUpdateAPIRequestDTO {
    /**
     * 
     * @type {Array<UsersUpdateAPIUserDTO>}
     * @memberof UsersUpdateAPIRequestDTO
     */
    'users'?: Array<UsersUpdateAPIUserDTO>;
}

