/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersDeleteAPIRequestDTO
 */
export interface UsersDeleteAPIRequestDTO {
    /**
     * A list of objects representing users to delete.
     * @type {Array<string>}
     * @memberof UsersDeleteAPIRequestDTO
     */
    'userIds'?: Array<string>;
}

