/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersToUserGroupRequestDTO
 */
export interface UsersToUserGroupRequestDTO {
    /**
     * The unique identifier associated with the user group.
     * @type {string}
     * @memberof UsersToUserGroupRequestDTO
     */
    'userGroupId'?: string;
    /**
     * A list of strings representing unique user IDs to assign to or remove from the user group.
     * @type {Array<string>}
     * @memberof UsersToUserGroupRequestDTO
     */
    'userIds'?: Array<string>;
}

