/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserCreationAPIRequestDTO } from './user-creation-apirequest-dto';

/**
 * 
 * @export
 * @interface UsersCreationAPIRequestDTO
 */
export interface UsersCreationAPIRequestDTO {
    /**
     * A list of objects representing users to create.
     * @type {Array<UserCreationAPIRequestDTO>}
     * @memberof UsersCreationAPIRequestDTO
     */
    'users'?: Array<UserCreationAPIRequestDTO>;
}

