/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsersToUserGroupRequestDTO } from './users-to-user-group-request-dto';

/**
 * 
 * @export
 * @interface UsersToUserGroupsRequestDTO
 */
export interface UsersToUserGroupsRequestDTO {
    /**
     * A list of objects representing the user groups and users to assign or remove.
     * @type {Array<UsersToUserGroupRequestDTO>}
     * @memberof UsersToUserGroupsRequestDTO
     */
    'userGroups'?: Array<UsersToUserGroupRequestDTO>;
}

