/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersAPIErrorMessageDTO
 */
export interface UsersAPIErrorMessageDTO {
    /**
     * Error message
     * @type {string}
     * @memberof UsersAPIErrorMessageDTO
     */
    'message'?: string;
    /**
     * The unique identifier associated to this error
     * @type {string}
     * @memberof UsersAPIErrorMessageDTO
     */
    'rci'?: string;
}

