/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AllPermissionsAssignedForLocalTenantDTO } from './all-permissions-assigned-for-local-tenant-dto';
import { AllProfileAssignedForLocalTenantDTO } from './all-profile-assigned-for-local-tenant-dto';
import { AllUserGroupsAssignedForLocalTenantDTO } from './all-user-groups-assigned-for-local-tenant-dto';
import { LastLoginDTO } from './last-login-dto';

/**
 * 
 * @export
 * @interface UserGetAPIResponseDTO
 */
export interface UserGetAPIResponseDTO {
    /**
     * The unique identifier associated with the user.
     * @type {string}
     * @memberof UserGetAPIResponseDTO
     */
    'userId'?: string;
    /**
     * The user\'s username. This is typically the user\'s email, such as john@jupiter.com.
     * @type {string}
     * @memberof UserGetAPIResponseDTO
     */
    'username'?: string;
    /**
     * An identifiable name to display within Visier. For example, \"John Smith\".
     * @type {string}
     * @memberof UserGetAPIResponseDTO
     */
    'displayName'?: string;
    /**
     * If applicable, and if available, the user employee ID in the data.
     * @type {string}
     * @memberof UserGetAPIResponseDTO
     */
    'employeeId'?: string;
    /**
     * If false, the user account is disabled.
     * @type {boolean}
     * @memberof UserGetAPIResponseDTO
     */
    'accountEnabled'?: boolean;
    /**
     * A list of objects representing the list of available profiles.
     * @type {AllProfileAssignedForLocalTenantDTO}
     * @memberof UserGetAPIResponseDTO
     */
    'profiles'?: AllProfileAssignedForLocalTenantDTO;
    /**
     * A list of objects representing the user\'s permissions.
     * @type {AllPermissionsAssignedForLocalTenantDTO}
     * @memberof UserGetAPIResponseDTO
     */
    'permissions'?: AllPermissionsAssignedForLocalTenantDTO;
    /**
     * A list of objects representing the available user groups.
     * @type {AllUserGroupsAssignedForLocalTenantDTO}
     * @memberof UserGetAPIResponseDTO
     */
    'userGroups'?: AllUserGroupsAssignedForLocalTenantDTO;
    /**
     * An object that represents the time that the user last logged into Visier.
     * @type {LastLoginDTO}
     * @memberof UserGetAPIResponseDTO
     */
    'lastLogin'?: LastLoginDTO;
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof UserGetAPIResponseDTO
     */
    'email'?: string;
}

