/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserGroupAssignedForLocalTenantDTO
 */
export interface UserGroupAssignedForLocalTenantDTO {
    /**
     * The user group ID.
     * @type {string}
     * @memberof UserGroupAssignedForLocalTenantDTO
     */
    'userGroupId'?: string;
    /**
     * An identifiable user group name to display in Visier, such as \"Leadership User Group\".
     * @type {string}
     * @memberof UserGroupAssignedForLocalTenantDTO
     */
    'displayName'?: string;
}

