/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsersAPIErrorMessageDTO } from './users-apierror-message-dto';

/**
 * 
 * @export
 * @interface UsersAPIFailureDTO
 */
export interface UsersAPIFailureDTO {
    /**
     * The unique identifier associated with the user.
     * @type {string}
     * @memberof UsersAPIFailureDTO
     */
    'userId'?: string;
    /**
     * The user\'s username. This is typically the user\'s email, such as john@jupiter.com.
     * @type {string}
     * @memberof UsersAPIFailureDTO
     */
    'userName'?: string;
    /**
     * An identifiable name to display within Visier. For example, \"John Smith\".
     * @type {string}
     * @memberof UsersAPIFailureDTO
     */
    'displayName'?: string;
    /**
     * The error thrown during creation.
     * @type {UsersAPIErrorMessageDTO}
     * @memberof UsersAPIFailureDTO
     */
    'error'?: UsersAPIErrorMessageDTO;
}

