/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsersAPIFailureDTO } from './users-apifailure-dto';
import { UsersAPISuccessDTO } from './users-apisuccess-dto';

/**
 * 
 * @export
 * @interface UsersAPIResponseDTO
 */
export interface UsersAPIResponseDTO {
    /**
     * The users for which the request succeeded.
     * @type {Array<UsersAPISuccessDTO>}
     * @memberof UsersAPIResponseDTO
     */
    'successes'?: Array<UsersAPISuccessDTO>;
    /**
     * The users for which the request failed.
     * @type {Array<UsersAPIFailureDTO>}
     * @memberof UsersAPIResponseDTO
     */
    'failures'?: Array<UsersAPIFailureDTO>;
}

