/*
Visier User Management APIs

Visier APIs for managing users within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGroupsUsersForTenantDTO } from './user-groups-users-for-tenant-dto';

/**
 * 
 * @export
 * @interface UserGroupsUsersDTO
 */
export interface UserGroupsUsersDTO {
    /**
     * A list of objects representing the users that are explicitly assigned to the user group, organized by the tenants the users belong to.
     * @type {Array<UserGroupsUsersForTenantDTO>}
     * @memberof UserGroupsUsersDTO
     */
    'tenants'?: Array<UserGroupsUsersForTenantDTO>;
    /**
     * The limit of results to return. The maximum value is 1000.
     * @type {number}
     * @memberof UserGroupsUsersDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving values from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof UserGroupsUsersDTO
     */
    'start'?: number;
}

